### ISSUE TITLE
Possible wrong normalization of latitude and longitude

### ISSUE THREAD

**Issue by aglenis** [merlintang/SpatialSpark#1]
I think I found a bug in the space filling curve implementation: 
more specifically in the following lines from sfcurve.scala:

class HilbertCurve2D(resolution: Int) extends SpaceFillingCurve2D {
  val precision = math.pow(2, resolution).toLong
  val chc = new CompactHilbertCurve(Array(resolution, resolution))

  final def getNormalizedLongitude(x: Double): Long =
    ((x + 180) \* (precision - 1) / 360d).toLong
}
if we have a hilbert curve of precision (4,4) shouldn't latitude and longitude fall in the range [0,3].
As I see it implemented here they would fall in the range [0,15].

I tested the code and it seems to be working correctly with un-normalized values.

**Comment by merlintang** [comment]
Thanks for informing me this, do you mean that this line "((x + 180) * (precision - 1) / 360d).toLong" is wrong? can you let me know the correct solution? I just use SpaceFillingCurve2D class for very small part of code, it will influence the performance.

**Comment by aglenis** [comment]
Yes, shouldn't it be "((x + 180) * (resolution - 1) / 360d).toLong" ?

The same also applies to latitude.

**Comment by merlintang** [comment]
thanks, I am fixing it.
