### ISSUE TITLE
 Compile Error

### ISSUE THREAD

**Issue by pzz2011** [merlintang/SpatialSpark#2]
In file SpatialRDDMain.scala, please modify `import cs.purdue.edu.spatialbloomfilter.qtreeUtil` into `import cs.purdue.edu.spatialindex.spatialbloomfilter.qtreeUtil` otherwise it will result compile error.

Besides, I cannot pass the test by typing `sbt test`

**Comment by pzz2011** [comment]
Can you give a "how to run" simply If you have time? :-)
thanks

**Comment by merlintang** [comment]
sure, I will add it soon.

**Comment by merlintang** [comment]
it is updated. thanks.
